### ISSUE TITLE
deep_sleep functions are now called just 'sleep'

### ISSUE THREAD

**Issue by schweini** [SensorsIot/ESP32-Deep-Sleep#1]
I was trying out your sketches, and none of these deep sleep sketches worked. It seems all the functions like e.g.
esp_deep_sleep_enable_ext1_wakeup
are now called
esp_sleep_enable_ext1_wakeup
(without the 'deep')

This compiles and runs better.

I can't get esp_sleep_get_ext1_wakeup_status() to return anything other than 0, though. Ah well.

Thanks for your EXCELLENT videos, by the way! :-)

**Comment by don41382** [comment]
+1, same here

**Comment by SensorsIot** [comment]
Different commands in newer ESP32 versions
