### ISSUE TITLE
Maximum time to sleep? 3800 seconds leads to instant reboot.

### ISSUE THREAD

**Issue by zuernc** [SensorsIot/ESP32-Deep-Sleep#4]
I tried the TimerWakeUp.ino sketch on a LOLIN ESP32 and it is working fine. Except when I set `TIME_TO_SLEEP 3800` then the ESP wakes up immediately after running the sketch. `TIME_TO_SLEEP 1800` works without any issues. Tested it on a different board with the same result.
Am I missing something..?

**Comment by SensorsIot** [comment]
I assume the number is too big. I did not find a maximum time for deep-sleep in the datasheet.
maybe you try different numbers to find out where it starts to wake-up immediately. This is part of the ESP32 core implementation,

**Comment by zuernc** [comment]
I will do tryouts once I get closer to the ESP again :) The results shall be posted.

**Comment by zuernc** [comment]
Apparently every sleep cycle >2147 seconds leads to an immediate restart. Strange.

**Comment by soheils2** [comment]
> Apparently every sleep cycle >2147 seconds leads to an immediate restart. Strange.

it mean we have 35 minute 
thats imposible ! 
its lower than esp8266!

**Comment by SensorsIot** [comment]
Did you test it again? I did not. Maybe they changed it.

**Comment by SensorsIot** [comment]
It seems this is no more a limit. Maybe you talk to this guy: https://github.com/SensorsIot/DCF77-Transmitter-for-ESP32/pull/2#issuecomment-572765061

**Comment by deltazerorsan** [comment]
I'm using till 60 minutes deep sleep with no hustle...
